workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.reconstrect.visionboard"
        GOOGLE_PLAY_TRACK: internal
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: io.codemagic.reconstrect
      vars:
        BUNDLE_ID: "io.codemagic.reconstrect"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build iOS (no codesign first)
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA for testing
        script: |
          cd build/ios/Release-iphoneos
          mkdir -p ../../ipa
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r ../../ipa/reconstrect.ipa Payload/
          echo "IPA created successfully"
          ls -la ../../ipa/reconstrect.ipa
          echo "IPA size: $(du -h ../../ipa/reconstrect.ipa | cut -f1)"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/Release-iphoneos/Runner.app
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  flutter-test:
    name: Flutter Test
    max_build_duration: 60
    instance_type: linux_x2
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test --coverage
      - name: Flutter integration tests
        script: |
          flutter test integration_test
        ignore_failure: true
    artifacts:
      - coverage/lcov.info
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: false
          failure: true

  release-workflow:
    name: Release Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    environment:
      android_signing:
        - keystore_reference
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.reconstrect.visionboard
      groups:
        - google_play
        - app_store_connect
      vars:
        PACKAGE_NAME: "com.reconstrect.visionboard"
        BUNDLE_ID: "com.reconstrect.visionboard"
        GOOGLE_PLAY_TRACK: production
      flutter: stable
      java: 17
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build Android
        script: |
          flutter build appbundle --release
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true

  ios-testing-workflow:
    name: iOS Testing Build (No Signing)
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: new-merge-request
          include: true
          source: true
        - pattern: main
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS for testing (no signing)
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA for testing
        script: |
          mkdir -p build/ios/ipa
          cd build/ios/Release-iphoneos
          zip -r ../ipa/reconstrect_testing.ipa Runner.app
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false 