// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVphUfUW7vuzuUlkQrHpqgVcv8-ODfXso',
    appId: '1:633982729642:web:5c64c7ba8d203865f93fd3',
    messagingSenderId: '633982729642',
    projectId: 'recostrect3',
    authDomain: 'recostrect3.firebaseapp.com',
    storageBucket: 'recostrect3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVphUfUW7vuzuUlkQrHpqgVcv8-ODfXso',
    appId: '1:633982729642:android:5c64c7ba8d203865f93fd3',
    messagingSenderId: '633982729642',
    projectId: 'recostrect3',
    storageBucket: 'recostrect3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgXiXtK1AUCw7PBfb8yeQf-Uv11HC8bQ',
    appId: '1:633982729642:ios:8f39016234c7df13f93fd3',
    messagingSenderId: '633982729642',
    projectId: 'recostrect3',
    storageBucket: 'recostrect3.firebasestorage.app',
    iosClientId: '633982729642-p8p5svhsbuu6g18kmk8agshb5j92amkf.apps.googleusercontent.com',
    iosBundleId: 'com.reconstrect.visionboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrgXiXtK1AUCw7PBfb8yeQf-Uv11HC8bQ',
    appId: '1:633982729642:ios:8f39016234c7df13f93fd3',
    messagingSenderId: '633982729642',
    projectId: 'recostrect3',
    storageBucket: 'recostrect3.firebasestorage.app',
    iosClientId: '633982729642-p8p5svhsbuu6g18kmk8agshb5j92amkf.apps.googleusercontent.com',
    iosBundleId: 'com.reconstrect.visionboard',
  );
} 